name: skills
on: [push, pull_request]
jobs:
  skills:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: bx-shef/skills-standard/action@v1
        with:
          eval-key: ${{ secrets.BXSHEF_EVAL_KEY }}
